language: ruby

rvm:
 - 2.3.1

script:
 - bundle exec rake db:migrate --trace
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
 - bundle exec rake sunspot:start
 - bundle exec rake sunspot:reindex
 - bundle exec rspec -fd spec/
 - bundle exec rake sunspot:stop

after_success:
 - CI=true TRAVIS=true coveralls --verbose

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
   secure: $heroku_apikey
         
  app: helpperi
           
  run:
    - "rake db:migrate"
    - restart