---
development:
  cloud_name: helpperi
  api_key: $CLOUDINARY_API_KEY']
  api_secret: $CLOUDINARY_SECRET_KEY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: helpperi
  api_key: $CLOUDINARY_API_KEY
  api_secret: $CLOUDINARY_SECRET_KEY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: helpperi
  api_key: $CLOUDINARY_API_KEY
  api_secret: $CLOUDINARY_SECRET_KEY
  enhance_image_tag: true
  static_image_support: false
